// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ClassLibrary1
{
    public partial class Bar
    {
        [Key]
        public int Id { get; set; }
        public int FooId { get; set; }
        [StringLength(255)]
        public string Description { get; set; }

        [ForeignKey(nameof(FooId))]
        [InverseProperty("Bar")]
        public virtual Foo Foo { get; set; }
    }
}