// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ClassLibrary1
{
    public partial class Foo
    {
        public Foo()
        {
            Bar = new HashSet<Bar>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string Name { get; set; }

        [InverseProperty("Foo")]
        public virtual ICollection<Bar> Bar { get; set; }
    }
}